
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mysql://springboot-db.cd3omgwnvdqy.ap-northeast-2.rds.amazonaws.com:3306/showmethecode
    username: kibm63
    password: kimeuna*6315
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
    show-sql: true
  profiles:
    include: oauth

cloud:
  aws:
    credentials:
      accessKey: ${AWS_S3_ACCESS_KEY}
      secretKey: ${AWS_S3_SECRET_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}
    region:
      static: ap-northeast-2
    stack:
      auto: false


#logging:
#  level:
#    org.hibernate: trace
#


